### ISSUE TITLE
How to Add More Check For More Accuracy

### ISSUE THREAD

**Issue by bobRE12** [CursedLand/Cursed-Auto-Decryptor#1]
The Title

**Comment by CursedLand** [comment]
You Create it not me

**Comment by bobRE12** [comment]
what I'm trying to say is how can I add Add More Check

**Comment by bobRE12** [comment]
just tell me how to do it and I'll do it myself

**Comment by CursedLand** [comment]
Any thing mdtoken method name etc

**Comment by bobRE12** [comment]
what
