### ISSUE TITLE
Unreliable way to grab parameter values

### ISSUE THREAD

**Issue by NETKroks** [CursedLand/Cursed-Auto-Decryptor#3]
The current way on how you grab the parameter values is unreliable. Currently you start at the index of the call subtracted by the parameter count of that certain method. Then you just iterate until you reach the index of the call instruction again. While iterating you try to parse the few instructions in that given range. However this will fail in many scenarios.
If you for example have: 

 ldc.i4.s 10
 ldc.i4.s 10
 nop 
 nop
 call Decrypt(Int32, Int32)
 
 Your method of grabbing the values would fail because it ignores the two ldc.i4.s which actually are the two parameter values since it starts at the first nop to grab the values.
 But there are plenty other scenarios such as this one:
 
...
brtrue label1
ldc.i4.s 10
brfalse label2
label1: 
ldc.i4.s 11 
label2:
ldc.i4.s 10
call Decrypt(Int32, Int32)

Here you have two possible paths on what the paramter value could be. 

My suggestion would be to somehow get the call dependencies (call dependencies = all instructions which are important for the call)n and then emulate with for example Echo (https://github.com/Washi1337/Echo/) the call dependencies. Since it emulates the stack you just would have to emulate the corresponding dependencies and then grab the parameter values from the emulated stack if possible. By this you also don't have to care about nops etc.

**Comment by bobRE12** [comment]
maybe he just wants to use the dnlib

**Comment by NETKroks** [comment]
> maybe he just wants to use dnlib

Sorry, this issue is not related to the library he uses. It can be also done by using dnlib. It has nothing to do with the library the author uses.

**Comment by bobRE12** [comment]
mad 
![image](https://user-images.githubusercontent.com/77860073/113360080-6b4f5d80-938c-11eb-8565-311203b7c6cf.png)

**Comment by CursedLand** [comment]
im quite sure my way is reliable, second its open source program so goal you update it and fix bugs, third i said _de4dot usage is recommended_ so i do not see its problem i must fix. (And Echo not stable for some OpCodes.)

**Comment by NETKroks** [comment]
Your way is not reliable and I already said why. You don't even need to use Echo. Also de4dot won't help you in many many scenarios.

**Comment by CursedLand** [comment]
:/

**Comment by XenocodeRCE** [comment]
> im quite sure my way is reliable, second its open source program so goal you update it and fix bugs, third i said _de4dot usage is recommended_ so i do not see its problem i must fix. (And Echo not stable for some OpCodes.)

The fact that it is open source is meant to receive issues like this one to refer to them later on once you fixed the said issue.
Don't waste your time with useless things, who cares about a dark mode if the program doesn't do its job well in the first place ? 😢  Same goes for a koivm devirt. 
First make unsealer base strong and very stable, try not to rely on external deobfuscator to clean the code before unsealer is being used (de4dot could break the file, and you have no way to fix that)

**Comment by CursedLand** [comment]
> > im quite sure my way is reliable, second its open source program so goal you update it and fix bugs, third i said _de4dot usage is recommended_ so i do not see its problem i must fix. (And Echo not stable for some OpCodes.)
> 
> The fact that it is open source is meant to receive issues like this one to refer to them later on once you fixed the said issue.
> Don't waste your time with useless things, who cares about a dark mode if the program doesn't do its job well in the first place ? 😢 Same goes for a koivm devirt.
> First make unsealer base strong and very stable, try not to rely on external deobfuscator to clean the code before unsealer is being used (de4dot could break the file, and you have no way to fix that)

Thats not UnSealer 😂😂

**Comment by bobRE12** [comment]
lol
