### ISSUE TITLE
Methods from NestedTypes are ignored

### ISSUE THREAD

**Issue by 0x11DFE** [CursedLand/Cursed-Auto-Decryptor#4]
Add support for "Decrypting" or invoking (call it how you want) strings within methods inside nestedtypes.
And if you don't mind clean up a bit the code :')

**Comment by CursedLand** [comment]
Sure.

**Comment by CursedLand** [comment]
[This](https://github.com/CursedLand/Cursed-Auto-Decryptor/commit/008533178398f19ee114011dfb80715ffc6ccdf5) Commit Closes This Issue.
